### ISSUE TITLE
Error when deleting an object that doesn't exist

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#107]
In this case I tried to do DeletePerson with `identifier: "a uuid that wasn't in the db"`

```
{
  "errors": [
    {
      "message": "Cannot read property 'identifier' of null",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "DeletePerson"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'identifier' of null",
            "    at /app/src/transformers/subscriptionFieldTransformer.js:59:20",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": {
    "DeletePerson": null
  }
}
```

**Comment by ChristiaanScheermeijer** [comment]
Thanks for reporting @alastair, I've found the problem. This error is returned if the node doesn't exist in the database. However, while investigating, I've discovered that the delete mutation should even be running that particular code (only for create mutations).

I will submit a PR fixing this.
