### ISSUE TITLE
Can't run ce-api in docker with current package.json

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#16]
Running `docker-compose build` and `docker-compose up` results in the following error:

```
api_1    | internal/modules/cjs/loader.js:582
api_1    |     throw err;
api_1    |     ^
api_1    |
api_1    | Error: Cannot find module 'babel-runtime/helpers/objectWithoutProperties'
api_1    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
api_1    |     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
api_1    |     at Module.require (internal/modules/cjs/loader.js:636:17)
api_1    |     at require (internal/modules/cjs/helpers.js:20:18)
api_1    |     at Object.<anonymous> (/app/node_modules/neo4j-graphql-js/dist/index.js:8:33)
api_1    |     at Module._compile (internal/modules/cjs/loader.js:688:30)
api_1    |     at Module._compile (/app/node_modules/pirates/lib/index.js:99:24)
api_1    |     at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
api_1    |     at Object.newLoader [as .js] (/app/node_modules/pirates/lib/index.js:104:7)
api_1    |     at Module.load (internal/modules/cjs/loader.js:598:32)
api_1    | [nodemon] app crashed - waiting for file changes before starting...
```

I can fix this by also copying package-lock.json into the image at this point:
https://github.com/trompamusic/ce-api/blob/e2405618acb0c796b8b87b8d08d9b689cade3f08/Dockerfile#L6
before running npm install. It looks like there are some packages missing in package.json that still exist in the lock file. I'm not sure what the best way of re-synchronising these files are.

**Comment by ChristiaanScheermeijer** [comment]
@alastair has this been fixed for you in the latest release?

**Comment by alastair** [comment]
Yes, I tested it again and it seems to work for me.
