### ISSUE TITLE
Can query a MusicComposition's author with an inline fragment but not with named Fragment

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#17]
I created a Person and a MusicComposition and joined them together with `AddCreativeWorkInterfaceLegalPerson` and `field: author`

I can then query some Compositions and get their author by running the following query:
```
query {
  MusicComposition {
    identifier
    name
    author {
      ... on Person {
        identifier
        name
        source
      }
    }
  }
}
```
However, I also understand that I should be able to create a named fragment for the Person properties, such as 

```
query {
  MusicComposition {
    identifier
    name
    author {
      ... personFields
    }
  }
}

fragment personFields on Person {
  identifier
  name
  subject
}
```

This fails with:
```
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Person.name.",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:568:13)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:503:19)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:447:10)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:293:18)",
            "    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:717:10)",
            "    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:707:10)",
            "    at completeAbstractValue (/app/node_modules/graphql/execution/execute.js:664:10)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:593:12)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:503:19)",
            "    at /app/node_modules/graphql/execution/execute.js:623:25"
          ]
        }
```

**Comment by ChristiaanScheermeijer** [comment]
@alastair that is a bug indeed, but unfortunately, inline fragments aren't supported by the neo4j-graphql library.

For reference:

https://github.com/neo4j-graphql/neo4j-graphql-js/issues/103

**Comment by ChristiaanScheermeijer** [comment]
@alastair, this bug has been fixed 🎉

**Comment by alastair** [comment]
great, thanks!
